# Generated by Django 5.0.6 on 2024-06-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_contactinfo_restaurantinfo_alter_dish_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantinfo',
            name='image_name',
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
