# Generated by Django 5.0.6 on 2024-06-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_restaurantinfo_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
