# Generated by Django 5.0.6 on 2024-06-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='dish',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
