# Generated by Django 5.0.6 on 2024-06-19 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_remove_orderdetail_order_remove_orderdetail_dish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='dish',
            name='profit',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
