# Generated by Django 5.0.6 on 2024-06-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_table_alter_orderdetail_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('In attesa', 'In attesa'), ('In preparazione', 'In preparazione'), ('Pronto', 'Pronto')], default='In attesa', max_length=20),
        ),
    ]
