# Generated by Django 5.0.6 on 2024-06-20 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_alter_dish_price_alter_dish_profit'),
        ('orders', '0003_alter_orderdetail_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField()),
                ('dish1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_dish1', to='menu.dish')),
                ('dish2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_dish2', to='menu.dish')),
            ],
        ),
    ]
