# Generated by Django 5.0.6 on 2024-06-21 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_alter_dish_price_alter_dish_profit'),
        ('orders', '0004_similaritymatrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoOccurrenceMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('dish1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooccurrence_dish1', to='menu.dish')),
                ('dish2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooccurrence_dish2', to='menu.dish')),
            ],
        ),
    ]
